package org.apache.fulcrum.security.torque.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Mar 04 14:21:36 CET 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class TorqueTurbineRolePeerImpl
    extends org.apache.fulcrum.security.torque.om.BaseTorqueTurbineRolePeerImpl
    implements org.apache.fulcrum.security.torque.peer.TorqueTurbinePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1393939296083L;



}
