package org.apache.fulcrum.security.torque.om;

import java.sql.Connection;

import org.apache.fulcrum.security.entity.Group;
import org.apache.fulcrum.security.entity.Role;
import org.apache.fulcrum.security.entity.User;
import org.apache.torque.TorqueException;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Dec 21 09:31:58 CET 2020]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TorqueTurbineUserGroupRole
    extends org.apache.fulcrum.security.torque.om.BaseTorqueTurbineUserGroupRole
    implements org.apache.fulcrum.security.torque.peer.TurbineUserGroupRoleModelPeerMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1608539518006L;

	@Override
	public User getTurbineUser() throws TorqueException {
		return  getTorqueTurbineUser();
	}

	@Override
	public User getTurbineUser(Connection connection) throws TorqueException {
		return  getTorqueTurbineUser(connection);
	}

	@Override
	public Group getTurbineGroup() throws TorqueException {
		return  getTorqueTurbineGroup();
	}

	@Override
	public Group getTurbineGroup(Connection connection) throws TorqueException {
		return  getTorqueTurbineGroup(connection);
	}

	@Override
	public Role getTurbineRole() throws TorqueException {
		return  getTorqueTurbineRole();
	}

	@Override
	public Role getTurbineRole(Connection connection) throws TorqueException {
		return  getTorqueTurbineRole(connection);
	}



}
