package org.apache.fulcrum.security.torque.om;

import java.sql.Connection;

import org.apache.fulcrum.security.entity.Permission;
import org.apache.fulcrum.security.entity.Role;
import org.apache.fulcrum.security.model.turbine.entity.TurbinePermission;
import org.apache.torque.TorqueException;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Dec 21 09:31:57 CET 2020]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TorqueTurbineRolePermission
    extends org.apache.fulcrum.security.torque.om.BaseTorqueTurbineRolePermission
    implements org.apache.fulcrum.security.torque.peer.TurbineRolePermissionPeerMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1608539517996L;

	@Override
	public Role getTurbineRole() throws TorqueException {
		return getTorqueTurbineRole();
	}

	@Override
	public Role getTurbineRole(Connection connection) throws TorqueException {
		return  getTorqueTurbineRole(connection);
	}

	@Override
	public Permission getTurbinePermission() throws TorqueException {
		return  getTorqueTurbinePermission();
	}

	@Override
	public TurbinePermission getTurbinePermission(Connection connection) throws TorqueException {
		return  getTorqueTurbinePermission(connection);
	}



}
