package org.apache.fulcrum.security.torque.om;

import org.apache.fulcrum.security.torque.peer.TorqueTurbineUserGroupRolePeer;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Nov 27 14:37:43 CET 2017]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class TurbineUserGroupRolePeerImpl
    extends org.apache.fulcrum.security.torque.om.BaseTurbineUserGroupRolePeerImpl
    implements TorqueTurbineUserGroupRolePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1511789863339L;


}
