package org.apache.fulcrum.security.torque.om;

import org.apache.fulcrum.security.torque.peer.TorqueTurbinePeer;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 01 12:35:59 CEST 2016]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class TurbineUserPeerImpl
    extends org.apache.fulcrum.security.torque.om.BaseTurbineUserPeerImpl implements TorqueTurbinePeer<TurbineUser>
{
    /** Serial version */
    private static final long serialVersionUID = 1470047759103L;



}
